// src/components/MapView.vue
<template>
  <div class="w-full h-full relative">
    <div ref="mapContainer" class="w-full h-full"></div>
    <div
      v-if="hoveredFeature"
      class="absolute bg-white px-3 py-2 rounded shadow-lg text-sm pointer-events-none z-50 border border-gray-300"
      :style="{
        left: tooltipPosition.x + 'px',
        top: tooltipPosition.y + 'px',
      }"
    >
      <strong>ID:</strong>
      {{ hoveredFeature.id || hoveredFeature.properties?.id || "N/A" }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from "vue";
import { Deck } from "@deck.gl/core";
import { ScatterplotLayer, GeoJsonLayer } from "@deck.gl/layers";
import mapboxgl from "mapbox-gl";
import "mapbox-gl/dist/mapbox-gl.css";
import centroid from "@turf/centroid";
import { featureCollection } from "@turf/helpers";
import { MapboxOverlay } from '@deck.gl/mapbox';

const mapContainer = ref(null);
let deck: any = null;
let map: any = null;

const hoveredFeature = ref(null);
const tooltipPosition = ref({ x: 0, y: 0 });

const props = defineProps({
  data: {
    type: Array,
    default: [
      { position: [-122.4, 37.8], size: 100, color: [255, 0, 0] },
      { position: [-122.5, 37.9], size: 100, color: [0, 255, 0] },
      { position: [-122.3, 37.7], size: 100, color: [0, 0, 255] },
    ],
  },
  polygons: {
    type: Array,
    default: () => [],
  },
  viewState: {
    type: Object,
    default: () => ({
      longitude: -122.4,
      latitude: 37.8,
      zoom: 10,
      pitch: 0,
      bearing: 0,
    }),
  },
});

const getLayers = () => {
  const layers: any[] = [];
  const hoveredFeature = ref(null);

  // Add GeoJSON polygon layer if polygons are provided
  if (props.polygons && props.polygons.length > 0) {
    layers.push(
      new GeoJsonLayer({
        id: "geojson-layer",
        data: props.polygons as any, // Can be single or multiple polygons
        filled: true,
        stroked: true,
        getFillColor: (f) => f.properties.fillColor || [60, 165, 250, 100], // Semi-transparent blue
        getLineColor: [60, 60, 60, 255], // Solid blue outline
        getPointColor: [250, 165, 60, 255],
        getPointRadius: 10000,
        getLineWidth: 0.1,
        lineWidthMinPixels: 0.1,
        pickable: true,
        opacity: 0.15,
        onHover: (info: any) => {
          if (info.object) {
            hoveredFeature.value = info.object as any;
            tooltipPosition.value = { x: info.x, y: info.y };
          } else {
            hoveredFeature.value = null;
          }
        },
      }),
    );
  }

  return layers;
};

let overlay: any = null;

const initDeck = () => {
  if (!mapContainer.value) return;

  // Initialize Mapbox map
  map = new mapboxgl.Map({
    container: mapContainer.value as HTMLElement,
    style: "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json", // Free basemap, no token required
    center: [props.viewState.longitude, props.viewState.latitude],
    zoom: props.viewState.zoom,
    pitch: props.viewState.pitch,
    bearing: props.viewState.bearing,
    interactive: true,
    accessToken:
      "pk.eyJ1IjoieXV5YTczNyIsImEiOiJjbGY0ZmMzbG4wcjNvM3hxbTVqaWpqaDQ3In0.wkIMGbAn6HaRVqPs2CJSnA",
  });

  map.on("load", () => {
    overlay = new MapboxOverlay({
        layers: []
    });
    map.addControl(overlay);

    overlay.setProps({
      layers: getLayers()
    });

    // Create canvas for deck.gl
    const canvas = document.createElement("canvas");
    canvas.id = "deck-canvas";
    canvas.style.position = "absolute";
    canvas.style.left = "0";
    canvas.style.top = "0";
    canvas.style.width = "100%";
    canvas.style.height = "100%";
    canvas.style.pointerEvents = "auto"; // Enable pointer events for hover
    mapContainer.value.appendChild(canvas);

    // Initialize Deck.gl overlay
    deck = new Deck({
      canvas: canvas,
      width: "100%",
      height: "100%",
      initialViewState: {
        longitude: map.getCenter().lng,
        latitude: map.getCenter().lat,
        zoom: map.getZoom(),
        pitch: map.getPitch(),
        bearing: map.getBearing(),
      },
      controller: true, // Enable controller for hover events
      layers: getLayers(),
      getCursor: () => "default", // Keep default cursor, let map handle panning
    });

    // Sync deck.gl view with Mapbox map movements
    const updateDeckView = () => {
      if (deck && !deck._isUpdating) {
        deck.setProps({
          viewState: {
            longitude: map.getCenter().lng,
            latitude: map.getCenter().lat,
            zoom: map.getZoom(),
            pitch: map.getPitch(),
            bearing: map.getBearing(),
          },
        });
      }
    };

    // Sync Mapbox with deck.gl interactions
    deck.setProps({
      onViewStateChange: ({ viewState }: any) => {
        if (map && !map._isUpdating) {
          map._isUpdating = true;
          map.jumpTo({
            center: [viewState.longitude, viewState.latitude],
            zoom: viewState.zoom,
            bearing: viewState.bearing,
            pitch: viewState.pitch,
          });
          map._isUpdating = false;
        }
        return viewState;
      },
    });

    map.on("move", () => {
      map._isUpdating = true;
      updateDeckView();
      map._isUpdating = false;
    });
    map.on("zoom", updateDeckView);
    map.on("rotate", updateDeckView);
    map.on("pitch", updateDeckView);
  });
};

onMounted(() => {
  initDeck();
});

onUnmounted(() => {
  if (deck) {
    deck.finalize();
  }
  if (map) {
    map.remove();
  }
});

watch(
  () => props.data,
  () => {
    if (deck) {
      deck.setProps({
        layers: getLayers(),
      });
    }
  },
  { deep: true },
);

watch(props.polygons, () => {
    if(!overlay) return;
    
    overlay.setProps({
      layers: getLayers()
    });
});

watch(
  () => props.polygons,
  () => {
    if (deck) {
      deck.setProps({
        layers: getLayers(),
      });
    }
    // Move map to polygon centroid
    if (props.polygons && props.polygons.length > 0 && map) {
      let center;
      if (props.polygons.length === 1) {
        // Single polygon
        center = centroid(props.polygons[0] as any);
      } else {
        // Multiple polygons - create feature collection
        const fc = featureCollection(props.polygons as any);
        center = centroid(fc);
      }

      map.flyTo({
        center: center.geometry.coordinates,
        zoom: props.polygons.length === 1 ? 8 : 6,
        duration: 2000,
      });
    }
  },
  { deep: true },
);
</script>

<style scoped>
canvas {
  width: 100%;
  height: 100%;
}
</style>

// coeqwal-tier-visualization-react/src/components/MapView.tsx
import React, { useEffect, useRef, useState, useMemo } from 'react';
import mapboxgl from 'mapbox-gl';
import { MapboxOverlay } from '@deck.gl/mapbox';
import { GeoJsonLayer, ScatterplotLayer } from '@deck.gl/layers';
import centroid from '@turf/centroid';
import { featureCollection } from '@turf/helpers';

// Ensure Mapbox CSS is imported
import 'mapbox-gl/dist/mapbox-gl.css';

// Set your Mapbox token here or via environment variable
mapboxgl.accessToken = process.env.REACT_APP_MAPBOX_TOKEN || '';

interface Props {
  data?: any[]; // For ScatterplotLayer (if used)
  polygons?: any[]; // GeoJSON features to highlight
}

interface TooltipInfo {
  x: number;
  y: number;
  feature: any;
}



export const MapView: React.FC<Props> = ({ data = [], polygons = [] }) => {
  const mapContainerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<mapboxgl.Map | null>(null);
  const overlayRef = useRef<MapboxOverlay | null>(null);
  
  const [tooltip, setTooltip] = useState<TooltipInfo | null>(null);

  // 1. Initialize Map and Overlay
  useEffect(() => {
    if (!mapContainerRef.current) return;
    
    // Prevent double initialization in React Strict Mode
    if (mapRef.current) return;

    const map = new mapboxgl.Map({
      container: mapContainerRef.current,
      style: 'mapbox://styles/mapbox/light-v10', // Or your preferred style
      center: [-121.4944, 38.5816], // Default center (e.g., Sacramento)
      zoom: 6,
      pitch: 0,
      bearing: 0,
    });

    // Initialize Deck.GL Overlay
    const overlay = new MapboxOverlay({
      layers: [],
    });

    map.addControl(overlay as any);

    mapRef.current = map;
    overlayRef.current = overlay;

    // Cleanup on unmount
    return () => {
      map.remove();
      overlay.finalize();
    };
  }, []);

  // 2. Helper to generate layers
  // Wrapped in useMemo/function to be called inside effects
  const getLayers = () => {
    return [
      // Example Scatterplot Layer (from original default prop)
      new ScatterplotLayer({
        id: 'scatter-layer',
        data: data,
        getPosition: (d: any) => d.position,
        getFillColor: [255, 0, 0],
        getRadius: (d: any) => d.size,
        pickable: true,
      }),
      // The GeoJSON Polygon Layer
      new GeoJsonLayer({
        id: 'geojson-layer',
        data: polygons,
        pickable: true,
        stroked: true,
        filled: true,
        extruded: false,
        lineWidthScale: 20,
        lineWidthMinPixels: 2,
        getFillColor: [160, 160, 180, 100], // Semi-transparent fill
        getLineColor: [0, 255, 255, 255],   // Cyan outline
        getLineWidth: 1,
        onHover: (info) => {
          if (info.object) {
            setTooltip({
              x: info.x,
              y: info.y,
              feature: info.object,
            });
          } else {
            setTooltip(null);
          }
        },
      }),
    ];
  };

  // 3. Update Layers when props change
  useEffect(() => {
    if (overlayRef.current) {
      overlayRef.current.setProps({
        layers: getLayers(),
      });
    }
  }, [data, polygons]);

  // 4. Handle "Fly To" logic when polygons change
  useEffect(() => {
    if (!mapRef.current || !polygons || polygons.length === 0) return;

    try {
      let center;
      
      // Calculate centroid using Turf.js
      if (polygons.length === 1) {
        center = centroid(polygons[0]);
      } else {
        const fc = featureCollection(polygons);
        center = centroid(fc as any);
      }

      const [lng, lat] = center.geometry.coordinates;

      mapRef.current.flyTo({
        center: [lng, lat],
        zoom: 9, // Adjust zoom level as needed
        essential: true, // Animation will happen even if user has reduced motion enabled
      });

    } catch (error) {
      console.error("Error calculating centroid or flying to location:", error);
    }
  }, [polygons]);

  return (
    <div className="w-full h-full relative">
      {/* Map Container */}
      <div ref={mapContainerRef} className="w-full h-full" />

      {/* Tooltip */}
      {tooltip && (
        <div
          className="absolute bg-white px-3 py-2 rounded shadow-lg text-sm pointer-events-none z-50 border border-gray-300"
          style={{
            left: tooltip.x,
            top: tooltip.y,
            transform: 'translate(-50%, -100%)', // Shift up so cursor doesn't block it
            marginTop: '-10px'
          }}
        >
          <strong>ID: </strong>
          {tooltip.feature.id || tooltip.feature.properties?.id || "N/A"}
        </div>
      )}
    </div>
  );
};
