// coeqwal-tier-visualization-react/src/components/CategoryComparisonChart.tsx
import React, { useRef, useEffect, useMemo } from 'react';
import * as d3 from 'd3';

interface Objective {
  id: number;
  category: string;
  tier: string;
  baselineTier: string;
  [key: string]: any;
}

interface Props {
  objectives: Objective[];
  currentScenario: string;
  baselineScenario: string;
  categories: string[];
  tiers: string[];
}

const CategoryComparisonChart: React.FC<Props> = ({
  objectives,
  currentScenario,
  baselineScenario,
  categories,
  tiers,
}) => {
  const svgRef = useRef<SVGSVGElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // 1. Replicate Vue's 'computed' statistics logic
  const statsData = useMemo(() => {
    const stats = categories.map((category) => {
      const categoryObjectives = objectives.filter((obj) => obj.category === category);
      const total = categoryObjectives.length;

      if (total === 0) {
        return {
          category,
          improved: 0,
          worsened: 0,
          unchanged: 0,
          total: 0,
          improvedPct: 0,
          worsenedPct: 0,
          unchangedPct: 0,
        };
      }

      let improved = 0;
      let worsened = 0;
      let unchanged = 0;

      categoryObjectives.forEach((obj) => {
        const currentTierIndex = tiers.indexOf(obj.tier);
        const baselineTierIndex = tiers.indexOf(obj.baselineTier);

        // Assuming lower tier index is better (Tier 1 < Tier 2)
        if (currentTierIndex < baselineTierIndex) {
          improved++;
        } else if (currentTierIndex > baselineTierIndex) {
          worsened++;
        } else {
          unchanged++;
        }
      });

      return {
        category,
        improved,
        worsened,
        unchanged,
        total,
        improvedPct: (improved / total) * 100,
        worsenedPct: (worsened / total) * 100,
        unchangedPct: (unchanged / total) * 100,
      };
    });

    return stats;
  }, [objectives, categories, tiers]);

  // 2. Replicate the HTML Summary string logic
  const summaryHTML = useMemo(() => {
    const totalObjs = statsData.reduce((acc, curr) => acc + curr.total, 0);
    if (totalObjs === 0) return 'No data available.';

    const totalImproved = statsData.reduce((acc, curr) => acc + curr.improved, 0);
    const totalWorsened = statsData.reduce((acc, curr) => acc + curr.worsened, 0);
    
    // Simple formatting helper
    const fmt = (n: number) => ((n / totalObjs) * 100).toFixed(1) + '%';

    return `Across all categories, 
      <span class="font-bold text-blue-600"> ${totalImproved} (${fmt(totalImproved)}) </span> improved and 
      <span class="font-bold text-red-500"> ${totalWorsened} (${fmt(totalWorsened)}) </span> worsened 
      compared to the baseline.`;
  }, [statsData]);

  // 3. D3 Rendering Logic
  useEffect(() => {
    if (!svgRef.current || !containerRef.current) return;

    // Cleanup previous render (including tooltips)
    d3.select(svgRef.current).selectAll('*').remove();
    d3.select('body').selectAll('.chart-tooltip').remove();

    // Dimensions
    const margin = { top: 30, right: 30, bottom: 100, left: 60 }; // Increased bottom for rotated labels
    const width = containerRef.current.clientWidth - margin.left - margin.right;
    const height = containerRef.current.clientHeight - margin.top - margin.bottom;

    const svg = d3.select(svgRef.current)
      .attr('width', width + margin.left + margin.right)
      .attr('height', height + margin.top + margin.bottom)
      .append('g')
      .attr('transform', `translate(${margin.left},${margin.top})`);

    // Scales
    const x = d3.scaleBand()
      .range([0, width])
      .domain(statsData.map((d) => d.category))
      .padding(0.2);

    const y = d3.scaleLinear()
      .range([height, 0])
      .domain([0, 100]); // Percentage

    // Axes
    svg.append('g')
      .attr('transform', `translate(0,${height})`)
      .call(d3.axisBottom(x))
      .selectAll('text')
      .attr('transform', 'translate(-10,0)rotate(-45)')
      .style('text-anchor', 'end');

    svg.append('g').call(d3.axisLeft(y).tickFormat((d) => `${d}%`));

    // Tooltip Helper
    const showTooltip = (event: MouseEvent, d: typeof statsData[0], type: 'improved' | 'worsened') => {
      const tooltip = d3.select('body')
        .selectAll('.chart-tooltip')
        .data([d])
        .join('div')
        .attr('class', 'chart-tooltip')
        .style('position', 'absolute')
        .style('background', 'white')
        .style('border', '1px solid #ccc')
        .style('border-radius', '4px')
        .style('padding', '8px')
        .style('font-size', '12px')
        .style('pointer-events', 'none')
        .style('box-shadow', '0 2px 4px rgba(0,0,0,0.1)')
        .style('z-index', '1000');

      const content = type === 'improved'
        ? `<strong>${d.category}</strong><br/>
           <span style="color:#2c7fb8">Improved:</span> ${d.improved} (${d.improvedPct.toFixed(1)}%)<br/>
           Unchanged: ${d.unchanged} (${d.unchangedPct.toFixed(1)}%)<br/>
           Total: ${d.total}`
        : `<strong>${d.category}</strong><br/>
           <span style="color:#F87171">Worsened:</span> ${d.worsened} (${d.worsenedPct.toFixed(1)}%)<br/>
           Unchanged: ${d.unchanged} (${d.unchangedPct.toFixed(1)}%)<br/>
           Total: ${d.total}`;

      tooltip
        .html(content)
        .style('left', `${event.pageX + 10}px`)
        .style('top', `${event.pageY - 10}px`)
        .style('opacity', 1);
    };

    const hideTooltip = () => {
      d3.selectAll('.chart-tooltip').remove();
    };

    // Draw Bars (Split bars: Up for improved, Down for worsened? Or side-by-side?)
    // Based on standard comparison charts, we often stack or group them.
    // Here we will draw two bars per category: Blue for Improved, Red for Worsened.
    
    // We'll use a sub-scale for grouping if needed, or just overlay them if they represent total share.
    // But since they are independent percentages of the total, let's stack them or put them side-by-side.
    // A simple approach is "Diverging" or just two bars. Let's do side-by-side for clarity.

    const xSub = d3.scaleBand()
      .domain(['improved', 'worsened'])
      .range([0, x.bandwidth()])
      .padding(0.05);

    // Render Groups
    const barGroups = svg.selectAll('.bar-group')
      .data(statsData)
      .enter()
      .append('g')
      .attr('transform', (d) => `translate(${x(d.category)},0)`);

    // Improved Bar
    barGroups.append('rect')
      .attr('x', xSub('improved') || 0)
      .attr('y', (d) => y(d.improvedPct))
      .attr('width', xSub.bandwidth())
      .attr('height', (d) => height - y(d.improvedPct))
      .attr('fill', '#2c7fb8') // Blue
      .on('mouseover', (e, d) => showTooltip(e, d, 'improved'))
      .on('mouseout', hideTooltip);

    // Worsened Bar
    barGroups.append('rect')
      .attr('x', xSub('worsened') || 0)
      .attr('y', (d) => y(d.worsenedPct))
      .attr('width', xSub.bandwidth())
      .attr('height', (d) => height - y(d.worsenedPct))
      .attr('fill', '#F87171') // Red
      .on('mouseover', (e, d) => showTooltip(e, d, 'worsened'))
      .on('mouseout', hideTooltip);
      
    // Cleanup function when component unmounts
    return () => {
        d3.select('body').selectAll('.chart-tooltip').remove();
    };

  }, [statsData]);

  return (
    <div className="w-full h-full bg-white p-4 flex flex-col">
      <h3 className="text-base font-semibold text-gray-800 mb-1">
        Comparing {currentScenario} vs. {baselineScenario}
      </h3>
      
      {/* Container for SVG to measure dimensions */}
      <div className="flex-1 w-full relative" ref={containerRef}>
        <svg ref={svgRef} className="w-full h-full" style={{ display: 'block' }}></svg>
      </div>

      <p 
        className="text-sm text-gray-600 mb-3 italic mt-2"
        dangerouslySetInnerHTML={{ __html: summaryHTML }}
      />
    </div>
  );
};

export default CategoryComparisonChart;

// src/components/CategoryComparisonChart.vue
<template>
  <div class="w-full h-full bg-white p-4 flex flex-col">
    <h3 class="text-base font-semibold text-gray-800 mb-1">
      Category Comparison: {{ currentScenario }} vs {{ baselineScenario }}
    </h3>
    <div class="flex-1 w-full">
      <svg ref="svgRef" class="w-full h-full"></svg>
    </div>
    <p class="text-sm text-gray-600 mb-3 italic" v-html="summaryHTML"></p>
  </div>
</template>

<script setup>
import { ref, watch, onMounted, computed } from "vue";
import * as d3 from "d3";

const props = defineProps({
  objectives: {
    type: Array,
    required: true,
  },
  currentScenario: {
    type: String,
    required: true,
  },
  baselineScenario: {
    type: String,
    required: true,
  },
  categories: {
    type: Array,
    required: true,
  },
  tiers: {
    type: Array,
    required: true,
  },
});

const svgRef = ref(null);

const margin = { top: 30, right: 30, bottom: 150, left: 80 };

// Calculate statistics per category
const categoryStats = computed(() => {
  const stats = [];

  props.categories.forEach((category) => {
    const categoryObjectives = props.objectives.filter(
      (obj) => obj.category === category,
    );

    if (categoryObjectives.length === 0) {
      return;
    }

    let improved = 0;
    let worsened = 0;
    let unchanged = 0;

    categoryObjectives.forEach((obj) => {
      const currentTierIndex = props.tiers.indexOf(obj.tier);
      const baselineTierIndex = props.tiers.indexOf(obj.baselineTier);

      if (currentTierIndex < baselineTierIndex) {
        // Lower tier number = better (Tier 1 is better than Tier 2)
        improved++;
      } else if (currentTierIndex > baselineTierIndex) {
        worsened++;
      } else {
        unchanged++;
      }
    });

    const total = categoryObjectives.length;
    const improvedPct = (improved / total) * 100;
    const worsenedPct = (worsened / total) * 100;
    const unchangedPct = (unchanged / total) * 100;

    stats.push({
      category,
      improved,
      worsened,
      unchanged,
      total,
      improvedPct,
      worsenedPct,
      unchangedPct,
    });
  });

  return stats;
});

// Generate HTML version with bold categories and colored directions
const summaryHTML = computed(() => {
  const getDirection = (stat) => {
    const { improved, worsened, unchangedPct } = stat;

    // Thresholds for classification
    const DOMINANT_THRESHOLD = 70;
    const MAJORITY_THRESHOLD = 50;
    const MINORITY_THRESHOLD = 30;

    if (unchangedPct == 100) {
      return "unaffected";
    }

    // Mixed requires BOTH improved AND worsened objectives
    const hasBoth = improved > 0 && worsened > 0;

    const getPrefix = (percentInDirection) => {
      console.log("Percent in direction:", percentInDirection);
      if (percentInDirection > DOMINANT_THRESHOLD) {
        return "";
      }
      if (percentInDirection > MAJORITY_THRESHOLD) {
        return "mostly ";
      }
      if (percentInDirection > MINORITY_THRESHOLD) {
        return "some ";
      }
      return "slight ";
    };

    if (!hasBoth) {
      // Pure positive or negative (no mixing)
      if (improved > 0 && worsened === 0)
        return getPrefix(stat.improvedPct) + "positive";
      if (worsened > 0 && improved === 0)
        return getPrefix(stat.worsenedPct) + "negative";
    }

    // Has both - classify as mixed
    if (stat.improvedPct > DOMINANT_THRESHOLD) {
      return "positive";
    }

    if (stat.worsenedPct > DOMINANT_THRESHOLD) {
      return "negative";
    }

    if (stat.improvedPct > MAJORITY_THRESHOLD) {
      return "mostly positive";
    }

    if (stat.worsenedPct > MAJORITY_THRESHOLD) {
      return "mostly negative";
    }

    if (stat.improvedPct > stat.worsenedPct) {
      return "mixed-positive";
    }

    if (stat.worsenedPct > stat.improvedPct) {
      return "mixed-negative";
    }

    return "mixed-neutral";
  };

  const getDirectionColor = (direction) => {
    if (direction === "positive" || direction === "mostly positive") {
      return "#3B82F6"; // Blue
    }
    if (direction === "negative" || direction === "mostly negative") {
      return "#EF4444"; // Red
    }
    if (direction === "mixed-positive" || direction === "slight positive") {
      return "#60A5FA"; // Light blue
    }
    if (direction === "mixed-negative" || direction === "slight negative") {
      return "#F87171"; // Light red
    }
    return "#6B7280"; // Gray for neutral/unaffected
  };

  const formatCategoryGroup = (stats, directionText) => {
    const categories = stats
      .map((s) => `<strong>${s.category}</strong>`)
      .join(", ");
    const color = getDirectionColor(stats[0].direction);
    return `${categories} <span style="color: ${color};">${directionText}</span>`;
  };

  const categorizedStats = categoryStats.value.map((stat) => ({
    ...stat,
    direction: getDirection(stat),
  }));
  console.log(categorizedStats);

  // Group categories by direction
  const directionGroups = new Map();
  categorizedStats.forEach((stat) => {
    if (!directionGroups.has(stat.direction)) {
      directionGroups.set(stat.direction, []);
    }
    directionGroups.get(stat.direction).push(stat);
  });
  const parts = [];
  const directionOrder = [
    "positive",
    "mostly positive",
    "slight positive",
    "mixed-positive",
    "negative",
    "mostly negative",
    "slight negative",
    "mixed-negative",
    "mixed-neutral",
  ];

  directionOrder.forEach((direction) => {
    const stats = directionGroups.get(direction);
    console.log("Processing direction:", direction, stats);
    if (stats && stats.length > 0) {
      parts.push(formatCategoryGroup(stats, `show ${direction} effects`));
    }
  });

  const hasUnaffected = directionGroups.has("unaffected");

  if (parts.length === 0 && !hasUnaffected) {
    return "No significant changes detected.";
  }

  if (parts.length === 0 && hasUnaffected) {
    return "All categories remain unaffected.";
  }

  // Join with line breaks instead of commas
  let result = "";
  if (parts.length === 0) {
    result = "";
  } else {
    result = parts.join(".<br>");
  }

  // Add "the rest unaffected" on a new line if there are unaffected categories
  if (hasUnaffected) {
    if (result) {
      result +=
        '.<br><span style="color: #6B7280;">The rest remain unaffected</span>';
    } else {
      result =
        '<span style="color: #6B7280;">All categories remain unaffected</span>';
    }
  } else {
    result += ".";
  }

  return result;
});

const drawChart = () => {
  if (!svgRef.value || categoryStats.value.length === 0) return;

  const container = svgRef.value.parentElement;
  const containerRect = container.getBoundingClientRect();
  const width = containerRect.width;
  const height = containerRect.height;

  const svg = d3.select(svgRef.value);
  svg.selectAll("*").remove();

  svg.attr("width", width).attr("height", height);

  const chartWidth = width - margin.left - margin.right;
  const chartHeight = height - margin.top - margin.bottom;

  const g = svg
    .append("g")
    .attr("transform", `translate(${margin.left},${margin.top})`);

  // Scales
  const xScale = d3
    .scaleBand()
    .domain(categoryStats.value.map((d) => d.category))
    .range([0, chartWidth])
    .padding(0.3);

  const yScale = d3.scaleLinear().domain([-100, 100]).range([chartHeight, 0]);

  // Axes
  const xAxis = d3.axisBottom(xScale);
  const yAxis = d3
    .axisLeft(yScale)
    .ticks(10)
    .tickFormat((d) => `${Math.abs(d)}%`);

  // X-axis (at bottom)
  g.append("g")
    .attr("transform", `translate(0,${chartHeight * 1.1})`)
    .call(xAxis)
    .selectAll("text")
    .attr("transform", "rotate(-20)")
    .style("text-anchor", "end")
    .style("font-size", "12px");

  // Y-axis
  g.append("g").call(yAxis).style("font-size", "12px");

  // Zero line
  g.append("line")
    .attr("x1", 0)
    .attr("x2", chartWidth)
    .attr("y1", yScale(0))
    .attr("y2", yScale(0))
    .attr("stroke", "#666")
    .attr("stroke-width", 2);

  // Improved bars (blue, upward)
  g.selectAll(".improved-bar")
    .data(categoryStats.value)
    .enter()
    .append("rect")
    .attr("class", "improved-bar")
    .attr("x", (d) => xScale(d.category))
    .attr("y", (d) => yScale(d.improvedPct))
    .attr("width", xScale.bandwidth())
    .attr("height", (d) => yScale(0) - yScale(d.improvedPct))
    .attr("fill", "#3B82F6")
    .attr("opacity", 0.8)
    .on("mouseover", function (event, d) {
      d3.select(this).attr("opacity", 1);
      showTooltip(event, d, "improved");
    })
    .on("mouseout", function () {
      d3.select(this).attr("opacity", 0.8);
      hideTooltip();
    });

  // Worsened bars (red, downward)
  g.selectAll(".worsened-bar")
    .data(categoryStats.value)
    .enter()
    .append("rect")
    .attr("class", "worsened-bar")
    .attr("x", (d) => xScale(d.category))
    .attr("y", yScale(0))
    .attr("width", xScale.bandwidth())
    .attr("height", (d) => yScale(-d.worsenedPct) - yScale(0))
    .attr("fill", "#EF4444")
    .attr("opacity", 0.8)
    .on("mouseover", function (event, d) {
      d3.select(this).attr("opacity", 1);
      showTooltip(event, d, "worsened");
    })
    .on("mouseout", function () {
      d3.select(this).attr("opacity", 0.8);
      hideTooltip();
    });

  // Labels on bars
  g.selectAll(".improved-label")
    .data(categoryStats.value.filter((d) => d.improvedPct > 5))
    .enter()
    .append("text")
    .attr("class", "improved-label")
    .attr("x", (d) => xScale(d.category) + xScale.bandwidth() / 2)
    .attr("y", (d) => yScale(d.improvedPct) - 5)
    .attr("text-anchor", "middle")
    .attr("fill", "#1E40AF")
    .attr("font-size", "11px")
    .attr("font-weight", "600")
    .text((d) => `${d.improved}`);

  g.selectAll(".worsened-label")
    .data(categoryStats.value.filter((d) => d.worsenedPct > 5))
    .enter()
    .append("text")
    .attr("class", "worsened-label")
    .attr("x", (d) => xScale(d.category) + xScale.bandwidth() / 2)
    .attr("y", (d) => yScale(-d.worsenedPct) + 15)
    .attr("text-anchor", "middle")
    .attr("fill", "#991B1B")
    .attr("font-size", "11px")
    .attr("font-weight", "600")
    .text((d) => `${d.worsened}`);

  // Axis labels
  svg
    .append("text")
    .attr("transform", "rotate(-90)")
    .attr("x", -height / 2)
    .attr("y", 20)
    .attr("text-anchor", "middle")
    .style("font-size", "14px")
    .style("font-weight", "600")
    .text("Percentage of Tiers");

  // Legend
  const legend = svg
    .append("g")
    .attr("transform", `translate(${width - margin.right - 150}, 10)`);

  legend
    .append("rect")
    .attr("x", 0)
    .attr("y", 0)
    .attr("width", 20)
    .attr("height", 12)
    .attr("fill", "#3B82F6")
    .attr("opacity", 0.8);

  legend
    .append("text")
    .attr("x", 25)
    .attr("y", 10)
    .style("font-size", "12px")
    .text("Improved");

  legend
    .append("rect")
    .attr("x", 90)
    .attr("y", 0)
    .attr("width", 20)
    .attr("height", 12)
    .attr("fill", "#EF4444")
    .attr("opacity", 0.8);

  legend
    .append("text")
    .attr("x", 115)
    .attr("y", 10)
    .style("font-size", "12px")
    .text("Worsened");
};

const showTooltip = (event, d, type) => {
  const tooltip = d3.select("body").selectAll(".category-tooltip").data([null]);

  const tooltipEnter = tooltip
    .enter()
    .append("div")
    .attr("class", "category-tooltip")
    .style("position", "absolute")
    .style("background", "white")
    .style("border", "1px solid #ccc")
    .style("border-radius", "4px")
    .style("padding", "8px")
    .style("font-size", "12px")
    .style("pointer-events", "none")
    .style("box-shadow", "0 2px 4px rgba(0,0,0,0.1)")
    .style("z-index", "1000");

  const tooltipMerged = tooltipEnter.merge(tooltip);

  const content =
    type === "improved"
      ? `<strong>${d.category}</strong><br/>
         Improved: ${d.improved} (${d.improvedPct.toFixed(1)}%)<br/>
         Unchanged: ${d.unchanged} (${d.unchangedPct.toFixed(1)}%)<br/>
         Total: ${d.total}`
      : `<strong>${d.category}</strong><br/>
         Worsened: ${d.worsened} (${d.worsenedPct.toFixed(1)}%)<br/>
         Unchanged: ${d.unchanged} (${d.unchangedPct.toFixed(1)}%)<br/>
         Total: ${d.total}`;

  tooltipMerged
    .html(content)
    .style("left", event.pageX + 10 + "px")
    .style("top", event.pageY - 10 + "px")
    .style("opacity", 1);
};

const hideTooltip = () => {
  d3.select("body").selectAll(".category-tooltip").style("opacity", 0);
};

onMounted(() => {
  drawChart();
  window.addEventListener("resize", drawChart);
});

watch(
  () => [props.objectives, props.currentScenario, props.baselineScenario],
  () => {
    drawChart();
  },
  { deep: true },
);
</script>

<style scoped>
svg {
  font-family:
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, sans-serif;
}
</style>
